### PR TITLE
Bundler generates package object to handle several classes with same name

### PR DESCRIPTION
**Pull request by tyrcho**

### CODE REVIEW

**Comment by tyrcho** [comment]
#18

**Comment by tyrcho** [comment]
seems to be working fine, but we need some more tests before merging it.

**Comment by huiwang** [comment]
@tyrcho the failure in the CI should be fixed with #33

**Comment by tyrcho** [comment]
@huiwang  OK, I'll merge the #33 in this PR then.

I still need to implement the case of package with several components (com.truelaurel...), the output code does not compile.

**Comment by tyrcho** [comment]
@huiwang I've tested this and it LGTM (looks good to me), including a full test on real code.
Would you please have a look before merging it ?

**Comment by tyrcho** [comment]
@huiwang good idea ! was not straightforward because scala won't allow you to import 2 classes of the same name in the same scope, and we don't support things like import aliases. But I'm pretty happy with this new test case.

**Pull request merged**
