### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by azzzy**
The BundlerMain object's main should be invoked, not Bundler case class (which doesn't have a main method)

### CODE REVIEW

**Comment by tyrcho** [comment]
thanks @azzzy ! Any feedback on this project ?

**Comment by azzzy** [comment]
I just found out about it, I was in the process of writing something quite similar to the bundler, and then stumbled upon your project, guys. I'll leave more feedback once I start actively using it.

**Comment by huiwang** [comment]
@azzzy thx for the PR, are you also playing codingame?

**Comment by azzzy** [comment]
@huiwang  Yeah, I picked it up to refresh my knowledge of algorithms and to learn a bit more about Scala, which sadly I wasn't able to use in my daily job (and some Rust in the future hopefully). After 13-14 years of "enterprise" programming, I must say it is almost inexistent :(

I am still a newbie there, but I really like the platform.

**Pull request merged**
